version: '2'


services:
  mirror_c:
    build:
      context: ./Mirror
      dockerfile: Dockerfile
    environment:
      - deps=postgresql,python3
    expose:
      - "8080"

  client_c:
    build:
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "8082:80"
